name: Docker Build & Publish latest
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Docker Image (latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to your Dockerfile and other build context files
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/bocabitlabs/${{ github.repository }}

      - name: Build and Push client Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to your Dockerfile and other build context files
          file: docker.client.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-client:latest
          labels: |
            org.opencontainers.image.source=https://github.com/bocabitlabs/${{ github.repository }}